//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sep.Pcc.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACQURIERREQUEST
    {
        public ACQURIERREQUEST()
        {
            this.TRANSACTIONs = new HashSet<TRANSACTION>();
        }
    
        public int ACQURIER_REQUEST_ID { get; set; }
        public string PAN { get; set; }
        public System.DateTime ACQURIERTIMESTAMP { get; set; }
        public long ACQURIERORDERID { get; set; }
        public string SECURIYCODE { get; set; }
        public string CARDHOLDERNAME { get; set; }
        public System.DateTime DATE { get; set; }
    
        public virtual BANK BANK { get; set; }
        public virtual ICollection<TRANSACTION> TRANSACTIONs { get; set; }
    }
}
