//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sep.Pcc.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK
    {
        public BANK()
        {
            this.ACQURIERREQUESTs = new HashSet<ACQURIERREQUEST>();
            this.ISSUERRESPONSEs = new HashSet<ISSUERRESPONSE>();
        }
    
        public string PAN { get; set; }
        public string SERVICEURL { get; set; }
    
        public virtual ICollection<ACQURIERREQUEST> ACQURIERREQUESTs { get; set; }
        public virtual ICollection<ISSUERRESPONSE> ISSUERRESPONSEs { get; set; }
    }
}
