//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sep.Pcc.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        public string TRANSACTIONID { get; set; }
        public int ACQURIER_RQUEST_ID { get; set; }
        public int ISSUER_RESPONSE_ID { get; set; }
        public System.DateTime TRANSACTIONTIMESTAMP { get; set; }
    
        public virtual ACQURIERREQUEST ACQURIERREQUEST { get; set; }
        public virtual ISSUERRESPONSE ISSUERRESPONSE { get; set; }
    }
}
