//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sep.Bank.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANKORDER
    {
        public BANKORDER()
        {
            this.TRANSACTIONs = new HashSet<TRANSACTION>();
        }
    
        public long BANKORDER_ID { get; set; }
        public long PAYMENT_ID { get; set; }
        public string PAN { get; set; }
        public System.DateTime BANKORDERTIMESTAMP { get; set; }
        public bool IS_ISSUER { get; set; }
    
        public virtual CREDITCARD CREDITCARD { get; set; }
        public virtual TRANSACTION TRANSACTION { get; set; }
        public virtual ICollection<TRANSACTION> TRANSACTIONs { get; set; }
    }
}
