//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sep.Bank.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREDITCARD
    {
        public CREDITCARD()
        {
            this.BANKORDERs = new HashSet<BANKORDER>();
        }
    
        public string PAN { get; set; }
        public Nullable<long> ACCOUNT_ID { get; set; }
        public string SECURITYCODE { get; set; }
        public string CARDHOLDERNAME { get; set; }
        public System.DateTime DATE { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual ICollection<BANKORDER> BANKORDERs { get; set; }
    }
}
