//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sep.Bank.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public ACCOUNT()
        {
            this.CREDITCARDs = new HashSet<CREDITCARD>();
        }
    
        public long ACCOUNT_ID { get; set; }
        public decimal AMMOUNT { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string MERCHANT_ID { get; set; }
        public string MERCHANT_PASSWORD { get; set; }
    
        public virtual ICollection<CREDITCARD> CREDITCARDs { get; set; }
    }
}
