//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sep.Bank.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        public TRANSACTION()
        {
            this.BANKORDERs = new HashSet<BANKORDER>();
        }
    
        public long PAYMENT_ID { get; set; }
        public Nullable<long> BANKORDER_ID { get; set; }
        public decimal AMOUNT { get; set; }
        public long TRANSACTIONORDERID { get; set; }
        public System.DateTime TRANSACTIONTIMESTAMP { get; set; }
    
        public virtual ICollection<BANKORDER> BANKORDERs { get; set; }
        public virtual BANKORDER BANKORDER { get; set; }
    }
}
